<a href="https://colab.research.google.com/github/Deepanshu-8126/Pandas/blob/main/Pandas_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

merge(), join(), concat()

analogy - there are 3 diffrent departmenets
h rhas - employee name , ids
finance has - employe id , slaries
operatiions has - emp id ,, dep id
combiine file
merge join concat

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/netflix_titles.csv')
print(df.shape)
df.columns.tolist()
print(df.head(3))

(8807, 12)
  show_id     type                 title         director  \
0      s1    Movie  Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show         Blood & Water              NaN
2      s3  TV Show             Ganglands  Julien Leclercq

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...

In [ ]:
print(df.isnull().sum())
#

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
# 7.1 concat - stack add dataframe
# down or up add
# axis = 0 row and axis = 1 column

# netflix dataset under concat
# Netflix data Movies aur TV Shows mein baanto

# split
movies = df[df['type'] == 'Movie'].copy()
tv_shows = df[df['type'] == 'TV Show'].copy()

print(movies.shape)
print(tv_shows.shape)


# combined
combined = pd.concat([movies, tv_shows])
print(f"Combined:{combined.shape}")

combined.head(5)

(6131, 12)
(2676, 12)
Combined:(8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

In [ ]:
# concat important features
# ignore_iondex = True fresh index
combined = pd.concat([movies , tv_shows], ignore_index = True)

# keys — source track
combined = pd.concat([movies, tv_shows],
                     keys=['Movies', 'TV Shows'])
print(combined.loc['Movies'].head(3))
print(combined.loc['TV Shows'].head(3))

  show_id   type                             title  \
0      s1  Movie              Dick Johnson Is Dead
6      s7  Movie  My Little Pony: A New Generation
7      s8  Movie                           Sankofa

                        director  \
0                Kirsten Johnson
6  Robert Cullen, José Luis Ucha
7                   Haile Gerima

                                                cast  \
0                                                NaN
6  Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7  Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...

                                             country          date_added  \
0                                      United States  September 25, 2021
6                                                NaN  September 24, 2021
7  United States, Ghana, Burkina Faso, United Kin...  September 24, 2021

   release_year rating duration  \
0          2020  PG-13   90 min
6          2021     PG   91 min
7          1993  TV-MA  125 min

                                          listed_in  \
0                                     Documentaries
6                          Children & Family Movies
7  Dramas, Independent Movies, International Movies

                                         description
0  As her father nears the end of his life, filmm...
6  Equestria's divided. But a bright-eyed hero be...
7  On a photo shoot in Ghana, an American model s...
  show_id     type                  title         director  \
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN

                                                cast       country  \
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...  South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...           NaN
3                                                NaN           NaN

           date_added  release_year rating   duration  \
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season

                                           listed_in  \
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV

                                         description
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...

In [ ]:
# axis =1 side  add
basic_info = df[['show_id', 'type', 'title', 'release_year']]
extra_info = df[['rating', 'duration', 'listed_in']]

combined_cols = pd.concat([basic_info , extra_info], axis = 1)
print(combined_cols)

     show_id     type                  title  release_year rating   duration  \
0         s1    Movie   Dick Johnson Is Dead          2020  PG-13     90 min
1         s2  TV Show          Blood & Water          2021  TV-MA  2 Seasons
2         s3  TV Show              Ganglands          2021  TV-MA   1 Season
3         s4  TV Show  Jailbirds New Orleans          2021  TV-MA   1 Season
4         s5  TV Show           Kota Factory          2021  TV-MA  2 Seasons
...      ...      ...                    ...           ...    ...        ...
8802   s8803    Movie                 Zodiac          2007      R    158 min
8803   s8804  TV Show            Zombie Dumb          2018  TV-Y7  2 Seasons
8804   s8805    Movie             Zombieland          2009      R     88 min
8805   s8806    Movie                   Zoom          2006     PG     88 min
8806   s8807    Movie                 Zubaan          2015  TV-14    111 min

                                              listed_in
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

[8807 rows x 7 columns]

In [ ]:
# duplicates check iindex
try:
    pd.concat([movies, tv_shows], verify_integrity=True)
except ValueError as e:
    print(f"Error: {e}")

In [ ]:
# concat - 3 + dataframes
# divide data of netflix
old = df[df['release_year'] < 2000]
mid = df[(df['release_year'] >= 2000) & (df['release_year'] < 2015)]
new = df[df['release_year'] >= 2015]

old.shape
mid.shape
new.shape


# all theese three concat
all_combined = pd.concat([old,mid,new], ignore_index = True)

combined.shape  # 8807 rows
combined

              show_id     type                             title  \
Movies   0         s1    Movie              Dick Johnson Is Dead
         6         s7    Movie  My Little Pony: A New Generation
         7         s8    Movie                           Sankofa
         9        s10    Movie                      The Starling
         12       s13    Movie                      Je Suis Karl
...               ...      ...                               ...
TV Shows 8795   s8796  TV Show                   Yu-Gi-Oh! Arc-V
         8796   s8797  TV Show                        Yunus Emre
         8797   s8798  TV Show                         Zak Storm
         8800   s8801  TV Show                Zindagi Gulzar Hai
         8803   s8804  TV Show                       Zombie Dumb

                                    director  \
Movies   0                   Kirsten Johnson
         6     Robert Cullen, José Luis Ucha
         7                      Haile Gerima
         9                    Theodore Melfi
         12              Christian Schwochow
...                                      ...
TV Shows 8795                            NaN
         8796                            NaN
         8797                            NaN
         8800                            NaN
         8803                            NaN

                                                            cast  \
Movies   0                                                   NaN
         6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
         7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
         9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
         12    Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
...                                                          ...
TV Shows 8795  Mike Liscio, Emily Bauer, Billy Bob Thompson, ...
         8796  Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...
         8797  Michael Johnston, Jessica Gee-George, Christin...
         8800  Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...
         8803                                                NaN

                                                         country  \
Movies   0                                         United States
         6                                                   NaN
         7     United States, Ghana, Burkina Faso, United Kin...
         9                                         United States
         12                              Germany, Czech Republic
...                                                          ...
TV Shows 8795                                      Japan, Canada
         8796                                             Turkey
         8797      United States, France, South Korea, Indonesia
         8800                                           Pakistan
         8803                                                NaN

                       date_added  release_year rating   duration  \
Movies   0     September 25, 2021          2020  PG-13     90 min
         6     September 24, 2021          2021     PG     91 min
         7     September 24, 2021          1993  TV-MA    125 min
         9     September 24, 2021          2021  PG-13    104 min
         12    September 23, 2021          2021  TV-MA    127 min
...                           ...           ...    ...        ...
TV Shows 8795         May 1, 2018          2015  TV-Y7  2 Seasons
         8796    January 17, 2017          2016  TV-PG  2 Seasons
         8797  September 13, 2018          2016  TV-Y7  3 Seasons
         8800   December 15, 2016          2012  TV-PG   1 Season
         8803        July 1, 2019          2018  TV-Y7  2 Seasons

                                                       listed_in  \
Movies   0                                         Documentaries
         6                              Children & Family Movies
         7      Dramas, Independent Movies, International Movies
         9                                      Comedies, Dramas
         12                         Dramas, International Movies
...                                                          ...
TV Shows 8795                             Anime Series, Kids' TV
         8796                  International TV Shows, TV Dramas
         8797                                           Kids' TV
         8800  International TV Shows, Romantic TV Shows, TV ...
         8803             Kids' TV, Korean TV Shows, TV Comedies

                                                     description
Movies   0     As her father nears the end of his life, filmm...
         6     Equestria's divided. But a bright-eyed hero be...
         7     On a photo shoot in Ghana, an American model s...
         9     A woman adjusting to life after a loss contend...
         12    After most of her family is murdered in a terr...
...                                                          ...
TV Shows 8795  Now that he's discovered the Pendulum Summonin...
         8796  During the Mongol invasions, Yunus Emre leaves...
         8797  Teen surfer Zak Storm is mysteriously transpor...
         8800  Strong-willed, middle-class Kashaf and carefre...
         8803  While living alone in a spooky town, a young g...

[8807 rows x 12 columns]