<a href="https://colab.research.google.com/github/Deepanshu-8126/Pandas/blob/main/Pandas_03%2C4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 loc, iloc, Boolean Filtering & query()

In [1]:
# loc - find by label
# iloc - position number to find
# bollean filtering - find by conditons

In [2]:
# setup
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Titanic-Dataset.csv')
print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# 3.1 label based indexing
# label = index name  - default 0 ,1,2,3 thesee are the labels
# df.loc[row_label, column_label]


# case 1 single row
df.loc[0]


# case 2 - mulitple rows
df.loc[0:2]  # 0 1 2 three include

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [4]:
# case 3 specifi columns + specific column
#  row 0 name and age only colum n
df.loc[0,'Name']

print(df.loc[0, 'Age'])


# multiple columns of first row 0
print(df.loc[0,['Name','Age','Survived']])

22.0
Name        Braund, Mr. Owen Harris
Age                            22.0
Survived                          0
Name: 0, dtype: object

In [5]:
# case 4 - rows range + column range
# rows 0 to 4 , column name to age
print(df.loc[0:4,'Name':'Age'])

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [6]:
# case 5 - custom index with loc
df2 = df.set_index('Name')

# find with name
print(df2.loc['Braund, Mr. Owen Harris'])

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [7]:
# 3.2 iloc : position based indexing
# -- nummber based loaction 0 - first 1- second

# case 1 - single row
df.iloc[0] # first row
df.iloc[-1] # last row
df.iloc[5]    # 6th row

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [8]:
# case 2- row range
df.iloc[0:3] # exclude 0 1 2
df.iloc[5:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [9]:
# case 3- row + column position
df.iloc[0,3] # row , column
df.iloc[0,0:4] # columnss 0 to 3
df.iloc[0:5,0:4] # rows 0 to 4 and columns 0 to 3

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

In [10]:
# case 4- specific rows + specific columns  fromm list
df.iloc[[1,2,4],[0,2,4]] # list under list

   PassengerId  Pclass     Sex
1            2       1  female
2            3       3  female
4            5       3    male

In [11]:
# cae 5 - useful tricks
# first 5 rows all columns
df.iloc[:5, :]

# alll rows and first 3 columns
df.iloc[:,:3]

# lasat 3 rows and last 2 columns
df.iloc[-3:,-2:]

    Cabin Embarked
888   NaN        S
889  C148        C
890   NaN        Q

In [12]:
# same result diffrent way
df.loc[0:2,'Name':'Sex']
df.iloc[0:3,2:5]

   Pclass                                               Name     Sex
0       3                            Braund, Mr. Owen Harris    male
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2       3                             Heikkinen, Miss. Laina  female

Boolean filtering

In [13]:
condition = df['Age']>30
df.shape # 891 12
# dataframe filter
old_passengers = df[condition]
old_passengers.shape # filter whose age is 30+ returned filtering

(305, 12)

In [14]:
# single condition
# 1st class pasengers
first_class = df[df['Pclass']==1]
print(first_class.shape) # 216,12


# female passengers
females = df[df['Sex']=='female']
print(females.shape)


# fare > 100
rich = df[df['Fare']>100]
rich.shape


# survived passengers
survived = df[df['Survived']==1]
survived.shape #  324 12

(216, 12)
(314, 12)

(342, 12)

In [15]:
# multiple conditions AND (&), OR (|), NOT (~)
# female and survived
female_survived = df[(df['Sex']=='female') & df['Survived']==1]
female_survived

# 1 st class and age>50
rich_old = df[(df['Pclass']==1) & (df['Age']>50)]
rich_old

# or - one condition satisfy
result = df[(df['Pclass']==1) | (df['Survived']==1)]
result

# not reverse the condition
males = df[~(df['Sex']=='female')]
# males passengers not female

In [16]:
# .isin() - multiple values check - is in the list

# pclass 1 or 2 passengers
upper_class = df[df['Pclass'].isin([1,2])]
print(upper_class)

result = df[df['Embarked'].isin(['S', 'C'])]
print(result.shape)

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
9             10         1       2
11            12         1       1
..           ...       ...     ...
880          881         1       2
883          884         0       2
886          887         0       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
883                      Banfield, Mr. Frederick James    male  28.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
3        0            113803  53.1000  C123        S
6        0             17463  51.8625   E46        S
9        0            237736  30.0708   NaN        C
11       0            113783  26.5500  C103        S
..     ...               ...      ...   ...      ...
880      1            230433  26.0000   NaN        S
883      0  C.A./SOTON 34068  10.5000   NaN        S
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C

[400 rows x 12 columns]
(812, 12)

In [17]:
#.between range check
# between(a,b)

# age 20 and 30 between
young_adults = df[df['Age'].between(20,30)]
young_adults.shape


# fare 10 to 50
mid_fare = df[df['Fare'].between(10,50)]
mid_fare.shape

(395, 12)

In [18]:
# .str methods = text filtering
# str = string operations columnn apply

# in name .Mr one passengers
mr_passengers = df[df['Name'].str.contains('Mr')]
mr_passengers

# name in uppercase
df['Name_Upper']=df['Name'].str.upper()

#.str_lower

# length - str.len()

# first three characters
df['frst3']=df['Name'].str[:3]

In [19]:
# filtering  + specific columns
# question - female passengers then only name agae fare

result = df[df['Survived']==1][['Name','Age','Fare','Sex']]
result

                                                  Name   Age     Fare     Sex
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833  female
2                               Heikkinen, Miss. Laina  26.0   7.9250  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000  female
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0  11.1333  female
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0  30.0708  female
..                                                 ...   ...      ...     ...
875                   Najib, Miss. Adele Kiamie "Jane"  15.0   7.2250  female
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  83.1583  female
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0  26.0000  female
887                       Graham, Miss. Margaret Edith  19.0  30.0000  female
889                              Behr, Mr. Karl Howell  26.0  30.0000    male

[342 rows x 4 columns]

In [30]:
# real analysis in titanic
female_survival = df[df['Sex'] == 'female']['Survived'].mean() * 100
print(f"{female_survival:.1f}%")

print("Male survival rate:")
male_survival = df[df['Sex'] == 'male']['Survived'].mean() * 100
print(f"{male_survival:.1f}%")


# in 1st class how many survived
print("1 st class survived")
first_class = df[(df['Pclass']==1) & (df['Survived']==1)]
print(f"1st class survivors {len(first_class)}")



# fare
max_fare_person = df.iloc[df['Fare'].idxmax()]
print(max_fare_person)

max_fare_person = df.loc[df['Fare'].idxmax(), ['Name', 'Fare', 'Pclass']]
print(max_fare_person)

74.2%
Male survival rate:
18.9%
1 st class survived
1st class survivors 136
PassengerId                 259
Survived                      1
Pclass                        1
Name           Ward, Miss. Anna
Sex                      female
Age                        35.0
SibSp                         0
Parch                         0
Ticket                 PC 17755
Fare                   512.3292
Cabin                       NaN
Embarked                      C
Name_Upper     WARD, MISS. ANNA
frst3                       War
Name: 258, dtype: object
Name      Ward, Miss. Anna
Fare              512.3292
Pclass                   1
Name: 258, dtype: object

In [58]:
# 3.4 query
# normal filtering
df[df['Age']>30]


# query - very clean
df.query('Age>30')

#Multiple conditions
df.query('Age > 30 and Pclass == 1').head(5)

df.query('Sex == "female" and Survived == 1')


"""df.query('Age between 20 and 30')
df.query('Pclass in [1, 2]')"""

# variable use in query
min_age = 25
df.query('Age > @min_age').head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_Upper,frst3
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",Cum
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"HEIKKINEN, MISS. LAINA",Hei
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)",Fut
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"ALLEN, MR. WILLIAM HENRY",All
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,"MCCARTHY, MR. TIMOTHY J",McC
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,"JOHNSON, MRS. OSCAR W (ELISABETH VILHELMINA BERG)",Joh