<a href="https://colab.research.google.com/github/Deepanshu-8126/Pandas/blob/main/Pandas_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# series  ( 5 methods to create series )
marks = pd.Series([85,90,78,92,88])
print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [3]:
# custom index
marks = pd.Series([85,90,78,92,88], index = ['Math','Science','English','Hindi', 'sst'])
print(marks)

Math       85
Science    90
English    78
Hindi      92
sst        88
dtype: int64

In [5]:
# dictionary
prices = {'Apple': 150, 'Mango': 80, 'Banana': 40}
s = pd.Series(prices )
s

Apple     150
Mango      80
Banana     40
dtype: int64

In [7]:
# from scalar
s = pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64

In [9]:
# numpy array
arr = np.array([10,20,30,40])
s = pd.Series(arr)
s

0    10
1    20
2    30
3    40
dtype: int64

In [25]:
# topic 1.3 indexing and access
marks = pd.Series([85, 90, 78, 92, 88],
                  index=['Math','Science','English','Hindi','SST'])

print(marks[0])
print(marks[2])

# custom label
print(marks['Math'])

# mulitple labels double brackets
marks[['Math','Hindi']]

85
78
85

/tmp/ipykernel_1155/2551858516.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[0])
/tmp/ipykernel_1155/2551858516.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(marks[2])

Math     85
Hindi    92
dtype: int64

In [ ]:
# series attributes
print(marks.values)
print(marks.dtype)
print(marks.size)
print(marks.name) # series name
print(marks.index)

In [30]:
# Topic : series operations
# note : operation element wise
s = pd.Series([10, 20, 30, 40, 50])
print(s+5) # add 5 in all element
print(s*2)
print(s**2) # square of each
print(s / 10 )  # divide each by 10
print(s % 3)

0    15
1    25
2    35
3    45
4    55
dtype: int64
0     20
1     40
2     60
3     80
4    100
dtype: int64
0     100
1     400
2     900
3    1600
4    2500
dtype: int64
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64
0    1
1    2
2    0
3    1
4    2
dtype: int64

In [31]:
# two series operations
s1 = pd.Series([10, 20, 30], index=['a','b','c'])
s2 = pd.Series([5,  10, 15], index=['a','b','c'])
print(s1+s2)

a    15
b    30
c    45
dtype: int64

In [32]:
# mismatches - nan comes
s1 = pd.Series([10, 20], index=['a','b'])
s2 = pd.Series([5,  15], index=['a','c']) # c is diffrent
print(s1+s2)

# a matched

# nan - not a number - matching index not identify

a    15.0
b     NaN
c     NaN
dtype: float64

In [35]:
# Comparison
s = pd.Series([85, 90, 78, 92, 88])
print(s>85)
print(s[s>85]) # filter only that elements who are greater than 85

0    False
1     True
2    False
3     True
4     True
dtype: bool
1    90
3    92
4    88
dtype: int64

In [52]:
# Topic : Series Important methods
marks.describe()
marks.sum()
marks.mean()
marks.min()
marks.max()
marks.idxmin()
marks.idxmax() # index of max
marks.sort_values()
marks.sort_index() # index to sort
marks.value_counts() # unique value counts
marks.nunique() #  unnique value  count
marks.unique() # values return
marks.isnull()
marks.isnull().sum() # null values sum
marks.dropna()  # null values remove
#marks.fillna()  # null values replace
#marks.apply(func) # function at every element

Math       85
Science    90
English    78
Hindi      92
SST        88
dtype: int64

In [61]:
import pandas as pd
import numpy as np
scores = pd.Series([85, 92, np.nan, 78, 95, 88, np.nan, 70],
                   index=['Ali','Raj','Sam','Tom','Priya','Dev','Mia','Zoe'])

scores.describe()
print(scores.isnull().sum()) # 2 null values

filled = scores.fillna(scores.mean())
filled

# top scorer check
print('Top scorer :', scores.idxmax(), scores.max())

scores[scores>85]


# apply() - grade assign
def get_grade(x):
  if pd.isna(x): return 'N/a',
  elif x >= 90:  return 'A',
  elif x >= 80:  return 'B',
  else:           return 'C'

print(scores.apply(get_grade))

2
Top scorer : Priya 95.0
Ali        (B,)
Raj        (A,)
Sam      (N/a,)
Tom           C
Priya      (A,)
Dev        (B,)
Mia      (N/a,)
Zoe           C
dtype: object