<a href="https://colab.research.google.com/github/Deepanshu-8126/Pandas/blob/main/Pandas_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Dataframe
# creating dataframe
# 1- dictionary
import pandas as pd
data = {
    'Name':    ['Ali', 'Raj', 'Sam', 'Priya'],
    'Age':     [20, 22, 21, 23],
    'Marks':   [85, 92, 78, 95],
    'City':    ['Delhi', 'Mumbai', 'Delhi', 'Chennai']
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks     City
0    Ali   20     85    Delhi
1    Raj   22     92   Mumbai
2    Sam   21     78    Delhi
3  Priya   23     95  Chennai

In [10]:
# 2 - list of dicitonaries
data = [
    {'Name': 'Ali',   'Marks': 85},
    {'Name': 'Raj',   'Marks': 92},
    {'Name': 'Sam',   'Marks': 78},
]
df = pd.DataFrame(data)
data

[{'Name': 'Ali', 'Marks': 85},
 {'Name': 'Raj', 'Marks': 92},
 {'Name': 'Sam', 'Marks': 78}]

In [11]:
# 3 - custom index
data = {
    'Name':    ['Ali', 'Raj', 'Sam', 'Priya'],
    'Age':     [20, 22, 21, 23],
    'Marks':   [85, 92, 78, 95],
    'City':    ['Delhi', 'Mumbai', 'Delhi', 'Chennai']
}
df = pd.DataFrame(data, index=['s1','s2','s3','s4'])
df

     Name  Age  Marks     City
s1    Ali   20     85    Delhi
s2    Raj   22     92   Mumbai
s3    Sam   21     78    Delhi
s4  Priya   23     95  Chennai

In [12]:
#  4- csv file
df = pd.red_csv('students.csv')
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')

AttributeError: module 'pandas' has no attribute 'red_csv'

In [15]:
# Topic dataframe - data inspectionn
# eda starting
import pandas as pd
df = pd.read_csv('/content/Titanic-Dataset.csv')
df.head()  # first 5 rows
df.head(10)
df.tail()
df.tail(3) # last 3


df.shape  # rows and columns
df.info()
df.describe()  # numeric column stats
df.dtypes   # every column data type
df.columns  # columns names list
df.index  # index info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

RangeIndex(start=0, stop=891, step=1)

In [16]:
# 2.4 important attributes dataframe ( 7  )
print(df.shape)
df.columns # columns name return
df.dtypes  # every column data type return
df.size # values total (10692)
df.ndim   # dimension 2

(891, 12)

2

In [17]:
# column selection
# single column - series return
df['Age']
print(type(df['Age'])) # series


# multiple columns - dataframe return
df[['Name', 'Age', 'Survived']]
print(type(df[["Name"]])) # double brackets dataframe

# dot notation
print(df.Age)   # DF['Age'] same

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [18]:
# 2.6 adding , renaming and dropping columns

# new column add
df['Fare_Inr'] = df['Fare']*83  # fare convert to inr

# column rename
df.rename(columns={'Survived': 'Did_Survive', 'Pclass': 'Class'}, inplace=True)


# column drop
#df.drop(columns=['PassengerId'], inplace=True)


# row drop by index
df.drop(index=[0,1], inplace = True)

In [1]:
# real dataset work titanic
import pandas as pd
df = pd.read_csv('/content/Titanic-Dataset.csv')

# basic look
df.shape
df.head()
print(df.isnull().sum())

# Step 3: Basic stats
print(df.describe())

# Step 4: Specific column analysis
print(df['Survived'].value_counts())
print(df['Pclass'].value_counts())

# step 5- survival rates
survival_rate = df['Survived'].mean() * 100
print(f'Survival Rate: {survival_rate:.2f}%')  # 38.38%

#step 6- new column - age group
df['Age_Group'] = df['Age'].apply(lambda x: 'Child' if x < 18 else 'Adult')
print(df[['Name','Age','Age_Group']].head(10))

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
Survived
0    549
1    342
Name: count, dtype: int64
Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Survival Rate: 38.38%
                                                Name   Age Age_Group
0                            Braund, Mr. Owen Harris  22.0     Adult
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0     Adult
2                             Heikkinen, Miss. Laina  26.0     Adult
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0     Adult
4                           Allen, Mr. William Henry  35.0     Adult
5                                   Moran, Mr. James   NaN     Adult
6                            McCarthy, Mr. Timothy J  54.0     Adult
7                     Palsson, Master. Gosta Leonard   2.0     Child
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0     Adult
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0     Child

Practice questions

In [40]:
# 1- dictionary dataframe create
data = {'Name': ['Deepanshu','Vishal','Mohit','Chandan','Himashu'],
             'Salary':[90000,13000,45000,45000,45000],
             'Department':['csa','sda','android','cloud','data science'],
             'Experience':[1,2,4,5,6]
             }
df=pd.DataFrame(data)
df.shape
df.columns # index return
df.dtypes


# 3-
df.head(3)
df.tail(2)


# 4- only select name and salary column
df[['Name','Salary']]


#5- new column add  tax
df['Tax']=df['Salary']*0.1
df['Tax']


# 6- column rename  salry - ctc
df.rename(columns={'Salary':'Ctc'},inplace = True)
df.head()

# 7- experience column drop
df.drop(columns=['Experience'],inplace=True)

# 8- describe()
df.describe()

#9 - info()
tt = pd.read_csv('/content/Titanic-Dataset.csv')
tt.info()
tt.isnull().sum()


# 12 -
tt['Pclass'].value_counts()

# 11 - survival rate using mean
tt['Survived'].mean()*100
tt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [46]:

# 13- salary basis new column add level
df.head()

# apply function

df['Level']=df['Ctc'].apply(lambda x: 'Senior' if x>80000 else 'junior')
df

        Name    Ctc    Department     Tax   Level
0  Deepanshu  90000           csa  9000.0  Senior
1     Vishal  13000           sda  1300.0  junior
2      Mohit  45000       android  4500.0  junior
3    Chandan  45000         cloud  4500.0  junior
4    Himashu  45000  data science  4500.0  junior

In [54]:
# question 14 - df.size df.shape
df.shape
df.size

25

In [56]:
# question 15 -
tt
tt[['Name','Age','Survived']].head(10)

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0
5                                   Moran, Mr. James   NaN         0
6                            McCarthy, Mr. Timothy J  54.0         0
7                     Palsson, Master. Gosta Leonard   2.0         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0         1